### ISSUE TITLE
Support line spacing

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-braille#26]
Depends on:
- [x] https://github.com/snaekobbi/braille-css-spec/issues/18
- [x] https://github.com/snaekobbi/braille-css/issues/5
- [x] https://github.com/joeha480/dotify/issues/132

**Comment by bertfrees** [comment]
@jukkae Maybe this is a good starting point for you to get familiar with the whole system? Explore what needs to be done in the various parts (CSS, OBFL, PEF, liblouis, dotify, pipeline-mod-braille; I list them all but not all will need work of course) to support line spacing and make an overview here.

**Comment by bertfrees** [comment]
I don't think there is a single straightforward solution for this problem. It very much depends on the granularity with which we want to configure line spacing.

Something I don't find in the requirements but that I know we talked about is that when alternating lines on odd and even pages ([4.4:75](http://dev.pef-format.org/dp2/master/index.xhtml#4.4:75)), the headers and footers might still have to overlap.

**Comment by bertfrees** [comment]
So @jukkae will investigate what needs to happen in the specification (https://github.com/snaekobbi/braille-css-spec/issues/18) and in the various components of the system to support line spacing. Then we'll discuss it together before putting the plan into practice.

**Comment by jukkae** [comment]
OBFL currently supports what we want to do with line-height satisfactorily, at least when we take into account a couple of peculiarities with margins. 

Suggestions for specification:
- Add line-height property to CSS specification. The property could be defined quite similarly to vanilla CSS: "On a block container whose content is composed of inline elements, 'line-height' specifies the height of line boxes within the element." Possible values are (at least for now) positive integers - this may be later modified to allow, for example, line-height of 1.5, which would correspond to row-gap="2" in PEF.
- Specify that line-height of an element explicitly does not affect margins of that element, ie. margins are absolute, not relative to line-height. However, line-height does affect the line box height also for the last line of the element. This, in effect, creates an empty space of one row that could be confused with an empty row caused by margins.
- Specify to which direction line-height extends the height of line boxes. It is easier to extend the height downwards, in other words, to add gap below the element. On the other hand, this contrasts with vanilla CSS's behavior and may be unintuitive.

Possible implementation:
- For the line-height of elements itself, the transformation from input file to OBFL should be quite simple, as line-height attribute described above maps directly to row-spacing attribute in OBFL.
- Margins are a bit trickier, because the current implementation of transformation from OBFL to PEF considers OBFL margins to be relative to row-spacing attribute. This means that if row-spacing="2.0" and margin-top="1.0", in PEF there will be two empty rows instead of one. This can, however, be circumvented during transformation to OBFL by wrapping elements with line-height not equal to 1 inside a block with row-spacing="1.0" and setting margins for the wrapper block instead of the original element.

**Comment by bertfrees** [comment]
Great!

I will take care of updating the CSS specification. @jukkae Do you want to give a shot at implementing line-height in mod-braille? The modules that need changes are braille-css (separate project now), css-utils and dotify-formatter.

We'll also need to update the CSS spec + implementation for giving an offset to verso-pages, but we can look at that afterwards.

**Comment by jukkae** [comment]
Sure, I'll have a look at the implementation.
Regarding verso pages, we can probably do something similar to what Joel did at MTM (extending verso page headers upwards by one row).

**Comment by bertfrees** [comment]
Yup, that's what I was thinking too. CSS need to be extended a little for that.

**Comment by joeha480** [comment]
I have updated the OBFL spec. to be a bit clearer about margins vs. row-spacing: 
https://github.com/joeha480/obfl/commit/fe32c15739a424c729b92625f3bff6d7a4f8885b

**Comment by bertfrees** [comment]
Nice. FYI I've updated the CSS spec too: https://github.com/snaekobbi/braille-css-spec/issues/18

**Comment by bertfrees** [comment]
@jukkae I looked at your last few commits. I'm unsure whether we need to support `line-height` inside `@page`. We never said we were going to do this (see [specification](http://snaekobbi.github.io/braille-css-spec/master/index.html#the-line-height-property)). Setting double line spacing document-wide can also be accomplished with:

``` css
* {
  line-height: 2;
}
```

I know that in plain CSS `line-height` is probably also allowed in `@page`, and that in OBFL `row-spacing` is allowed on `layout-master`, but I'm don't know if the behavior is identical (w.r.t. cascading etc.), so we need to be careful. You can implement this if you want, just make sure the behavior is correct according to CSS. I'll then update the braille CSS spec too.

**Comment by jukkae** [comment]
Hum, now that I think of it, it might not make much sense after all. Will check tomorrow what's the best course of action.

**Comment by bertfrees** [comment]
@jukkae: I've merged the double-line-spacing branch (a0875e1e7b27dc1ebf1b461f8ad77d16752129cf) and added commits 31a1b7f62896be04fd1997264986029cbea5a3a2 and f17e6372df9b6cd138b7696b74e881b1f53b8ca7 which add support for `@page:left` and `@page:right` in css-utils the way we have agreed on IRC. Now all that is left is to support `@page:left` and `@page:right` in dotify-formatter.

**Comment by jukkae** [comment]
Ok, very good. I'll have a look at this today.

**Comment by bertfrees** [comment]
See also https://github.com/joeha480/dotify/issues/132

**Comment by bertfrees** [comment]
Merged in 9669b5d5f191d0fbeb57a2188e42620e45036a08
